namespace BickersAction.Sage50Connector.Transport;

public interface IConnectorApiClient
{
    Task<HeartbeatResponse> SendHeartbeatAsync(
        HeartbeatRequest heartbeat,
        string machineCredential,
        CancellationToken cancellationToken);
    Task<CustomerLookupClaimResponse> ClaimCustomerLookupAsync(
        string machineCredential,
        CancellationToken cancellationToken);
    Task StartCustomerLookupAsync(
        string lookupJobId,
        string leaseToken,
        string machineCredential,
        CancellationToken cancellationToken);
    Task CompleteCustomerLookupAsync(
        string lookupJobId,
        string leaseToken,
        IReadOnlyList<CustomerLookupResultPayload> results,
        string machineCredential,
        CancellationToken cancellationToken);
    Task FailCustomerLookupAsync(
        string lookupJobId,
        string leaseToken,
        string code,
        string message,
        bool retryable,
        string machineCredential,
        CancellationToken cancellationToken);
    Task<InvoiceExportClaimResponse> ClaimInvoiceExportAsync(
        string machineCredential,
        CancellationToken cancellationToken);
    Task StartInvoiceExportAsync(
        string queueJobId,
        string leaseToken,
        string machineCredential,
        CancellationToken cancellationToken);
    Task CompleteInvoiceExportAsync(
        string queueJobId,
        string leaseToken,
        string sageInvoiceId,
        string invoiceNumber,
        DateOnly postedDate,
        string machineCredential,
        CancellationToken cancellationToken);
    Task FailInvoiceExportAsync(
        string queueJobId,
        string leaseToken,
        string code,
        string message,
        bool retryable,
        string machineCredential,
        CancellationToken cancellationToken);
}
