"use client";
import { Children,cloneElement,createElement,forwardRef,isValidElement,useEffect,useId,useRef,useState } from "react";
import { createPortal } from "react-dom";
import styles from "./ui.module.css";
const cx=(...v)=>v.filter(Boolean).join(" ");
export function Page({children,width="standard",className="",...p}){return <main data-app-page data-sidebar-page className={cx(styles.page,width==="fluid"&&styles.pageFluid,width==="readable"&&styles.pageReadable,className)} {...p}><div className={styles.pageInner}>{children}</div></main>}
export function PageHeader({title,subtitle,actions,className=""}){return <header data-app-page-header data-sidebar-page-header className={cx(styles.pageHeader,className)}><div className={styles.pageHeading}>{title&&<h1 className={styles.title}>{title}</h1>}{subtitle&&<p className={styles.subtitle}>{subtitle}</p>}</div>{actions&&<div data-app-page-actions className={styles.headerActions}>{actions}</div>}</header>}
export function Section({title,description,actions,children,className="",...p}){return <section className={cx(styles.section,className)} {...p}>{(title||description||actions)&&<div className={styles.sectionHeader}><div>{title&&<h2 className={styles.sectionTitle}>{title}</h2>}{description&&<p className={styles.sectionDescription}>{description}</p>}</div>{actions&&<div className={styles.headerActions}>{actions}</div>}</div>}{children}</section>}
export function Stack({as="div",direction="column",gap=3,className="",...p}){return createElement(as,{...p,className:cx(styles.stack,direction==="row"&&styles.row,styles[`gap${gap}`],className)})}
export function Grid({as="div",columns=1,gap=3,className="",style,...p}){return createElement(as,{...p,className:cx(styles.grid,className),style:{"--grid-columns":columns,"--grid-gap":`var(--space-${gap})`,...style}})}
export function Toolbar({children,className="",...p}){return <div className={cx(styles.toolbar,className)} {...p}>{children}</div>}
export function Card({as="div",interactive=false,className="",...p}){return createElement(as,{...p,"data-ui-card":"true",className:cx(styles.card,interactive&&styles.cardInteractive,className)})}
export function NavigationCard({title,description,icon,badges=[],disabled=false,className="",onClick,...p}){const badgeVariant=tone=>tone==="danger"?"danger":tone==="amber"||tone==="warning"?"warning":tone==="green"||tone==="success"?"success":tone==="info"?"info":"neutral";return <button type="button" data-ui-navigation-card="true" className={cx(styles.navigationCard,className)} disabled={disabled} onClick={onClick} title={disabled?"Unavailable":description} {...p}><span className={styles.navigationCardIcon} aria-hidden="true">{icon}</span><span className={styles.navigationCardBody}><strong className={styles.navigationCardTitle}>{title}</strong>{description&&<span className={styles.navigationCardDescription}>{description}</span>}{badges.length?<span className={styles.navigationCardBadges}>{badges.map((badge,index)=><Badge key={`${badge.label}-${index}`} variant={badgeVariant(badge.tone)}>{badge.label}</Badge>)}</span>:null}</span><span className={styles.navigationCardArrow} aria-hidden="true">›</span></button>}
export function MetricCard({label,value,valueSuffix="",hint="",icon,tone="neutral",onClick,disabled=false,className="",...p}){const normalized=tone==="critical"||tone==="danger"?"danger":tone==="urgent"||tone==="amber"||tone==="warning"?"warning":tone==="positive"||tone==="ok"||tone==="green"||tone==="success"?"success":tone==="brand"||tone==="soft"||tone==="info"?"info":"neutral";const C=onClick?"button":"div";return <C type={onClick?"button":undefined} data-ui-metric-card="true" className={cx(styles.metricCard,styles[`metricCard${normalized[0].toUpperCase()}${normalized.slice(1)}`],onClick&&styles.metricCardInteractive,className)} onClick={onClick} disabled={onClick?disabled:undefined} data-tone={normalized} {...p}><span className={styles.metricCardLabel}>{label}</span><strong className={styles.metricCardValue}>{value}{valueSuffix?<small>{valueSuffix}</small>:null}</strong><span className={styles.metricCardIcon} aria-hidden="true">{icon}</span>{hint?<span className={styles.metricCardHint}>{hint}</span>:null}{onClick?<span className={styles.metricCardArrow} aria-hidden="true">›</span>:null}</C>}
export function Panel({header,footer,children,className="",...p}){return <section data-ui-panel="true" className={cx(styles.panel,className)} {...p}>{header&&<div className={styles.panelHeader}>{header}</div>}<div className={styles.panelBody}>{children}</div>{footer&&<div className={styles.panelFooter}>{footer}</div>}</section>}
export function StatCard({label,value,hint,icon,className="",...p}){return <Card className={cx(styles.statCard,className)} {...p}>{icon}{label&&<span className={styles.statLabel}>{label}</span>}<strong className={styles.statValue}>{value}</strong>{hint&&<span className={styles.statHint}>{hint}</span>}</Card>}
export const Spinner=forwardRef(function Spinner({label="Loading",className="",...p},ref){return <span ref={ref} className={cx(styles.spinner,className)} role="status" aria-label={label} {...p}/>});
export const Button=forwardRef(function Button({as="button",variant="primary",size="md",bare=false,loading=false,disabled=false,className="",children,...p},ref){const C=as;return <C ref={ref} data-ui-button={bare?"bare":variant} data-ui-size={size} type={C==="button"?(p.type||"button"):p.type} className={cx(!bare&&styles.button,!bare&&styles[variant],!bare&&styles[`button${size[0].toUpperCase()}${size.slice(1)}`],loading&&styles.buttonLoading,className)} disabled={C==="button"?(disabled||loading):undefined} aria-disabled={C!=="button"?(disabled||loading):undefined} {...p}>{loading?<><Spinner className={styles.buttonSpinner}/><span className={styles.buttonContentLoading}>{children}</span></>:children}</C>});
export const IconButton=forwardRef(function IconButton({label,className="",...p},ref){return <Button ref={ref} className={cx(styles.iconButton,className)} aria-label={label} title={p.title||label} {...p}/>});
export function FormField({label,htmlFor,help,error,required=false,children,className=""}){const generated=useId(),id=htmlFor||generated;const child=isValidElement(Children.only(children))?cloneElement(Children.only(children),{id:Children.only(children).props.id||id,"aria-invalid":error||undefined}):children;return <div className={cx(styles.field,className)}>{label&&<label className={styles.label} htmlFor={id}>{label}{required&&<span className={styles.required}> *</span>}</label>}{child}{help&&<p className={styles.help}>{help}</p>}{error&&<p className={styles.error} role="alert">{error}</p>}</div>}
export function FormRow({columns=2,className="",style,...p}){return <div className={cx(styles.formRow,className)} style={{"--form-columns":columns,...style}} {...p}/>}
export const Input=forwardRef(function Input({bare=false,className="",...p},ref){return <input ref={ref} data-ui-control={bare?"bare":"input"} {...p} className={cx(!bare&&styles.control,className)}/>});export const Select=forwardRef(function Select({bare=false,className="",...p},ref){return <select ref={ref} data-ui-control={bare?"bare":"select"} {...p} className={cx(!bare&&styles.control,className)}/>});export const Textarea=forwardRef(function Textarea({bare=false,className="",...p},ref){return <textarea ref={ref} data-ui-control={bare?"bare":"textarea"} {...p} className={cx(!bare&&styles.control,!bare&&styles.textarea,className)}/>});export const Checkbox=forwardRef(function Checkbox({label,...p},ref){return <label className={styles.checkboxLabel}><input ref={ref} data-ui-control="checkbox" type="checkbox" {...p} className={styles.checkbox}/><span>{label}</span></label>});
export function Badge({variant="neutral",className="",...p}){return <span className={cx(styles.badge,variant!=="neutral"&&styles[`badge${variant[0].toUpperCase()}${variant.slice(1)}`],className)} {...p}/>};export function Alert({variant="neutral",className="",...p}){return <div role={variant==="danger"?"alert":"status"} className={cx(styles.alert,variant!=="neutral"&&styles[`alert${variant[0].toUpperCase()}${variant.slice(1)}`],className)} {...p}/>}
export function EmptyState({title,description,action,icon,className="",...p}){return <div className={cx(styles.emptyState,className)} {...p}><div>{icon}{title&&<h3 className={styles.emptyTitle}>{title}</h3>}{description&&<p className={styles.emptyDescription}>{description}</p>}{action&&<div className={styles.emptyAction}>{action}</div>}</div></div>}
export function Skeleton({width="100%",height=16,className="",style,...p}){return <span className={cx(styles.skeleton,className)} style={{display:"block",width,height,...style}} aria-hidden="true" {...p}/>}
export function Table({className="",...p}){return <table data-ui-table className={cx(styles.table,className)} {...p}/>};export function TableContainer({className="",...p}){return <div data-ui-table-container className={cx(styles.tableContainer,className)} {...p}/>}
export function Tabs({items=[],value,onChange,label="Sections",className=""}){return <div className={cx(styles.tabs,className)} role="tablist" aria-label={label}>{items.map(i=>{const key=i.value??i.key,active=key===value;return <button key={key} type="button" role="tab" aria-selected={active} className={cx(styles.tab,active&&styles.tabActive)} onClick={()=>onChange?.(key)}>{i.label}</button>})}</div>}
export function Modal({open,onClose,title,eyebrow,description,headerActions,children,footer,size="md",density="standard",closeLabel="Close",hideClose=false,className="",bodyClassName="",headerClassName="",footerClassName=""}){const ref=useRef(null),previous=useRef(null),onCloseRef=useRef(onClose),titleId=useId(),[mounted,setMounted]=useState(false);onCloseRef.current=onClose;useEffect(()=>setMounted(true),[]);useEffect(()=>{if(!open||!mounted)return;previous.current=document.activeElement;const overflow=document.body.style.overflow;document.body.style.overflow="hidden";ref.current?.focus();const key=e=>{if(e.key==="Escape")onCloseRef.current?.();if(e.key!=="Tab"||!ref.current)return;const focusable=[...ref.current.querySelectorAll('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')];if(!focusable.length){e.preventDefault();ref.current.focus();return}const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}};document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);document.body.style.overflow=overflow;previous.current?.focus?.()}},[open,mounted]);if(!open||!mounted)return null;const modal=<div className={styles.modalBackdrop} onMouseDown={e=>e.target===e.currentTarget&&onClose?.()}><section ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby={titleId} data-density={density} className={cx(styles.modal,styles[`modal${size[0].toUpperCase()}${size.slice(1)}`],className)}><header className={cx(styles.modalHeader,headerClassName)}><div className={styles.modalHeading}>{eyebrow&&<div className={styles.modalEyebrow}>{eyebrow}</div>}<h2 id={titleId} className={styles.modalTitle}>{title}</h2>{description&&<div className={styles.modalDescription}>{description}</div>}</div><div className={styles.modalHeaderActions}>{headerActions}{!hideClose&&<IconButton label={closeLabel} variant="ghost" size="sm" onClick={onClose} className={styles.modalClose}>×</IconButton>}</div></header>{children&&<div className={cx(styles.modalBody,bodyClassName)}>{children}</div>}{footer&&<footer className={cx(styles.modalFooter,footerClassName)}>{footer}</footer>}</section></div>;return createPortal(modal,document.body)}
