"use client";
import { Children,cloneElement,createElement,forwardRef,isValidElement,useEffect,useId,useRef } from "react";
import styles from "./ui.module.css";
const cx=(...v)=>v.filter(Boolean).join(" ");
export function Page({children,width="standard",className="",...p}){return <main className={cx(styles.page,width==="fluid"&&styles.pageFluid,width==="readable"&&styles.pageReadable,className)} {...p}><div className={styles.pageInner}>{children}</div></main>}
export function PageHeader({title,subtitle,actions,className=""}){return <header className={cx(styles.pageHeader,className)}><div className={styles.pageHeading}>{title&&<h1 className={styles.title}>{title}</h1>}{subtitle&&<p className={styles.subtitle}>{subtitle}</p>}</div>{actions&&<div className={styles.headerActions}>{actions}</div>}</header>}
export function Section({title,description,actions,children,className="",...p}){return <section className={cx(styles.section,className)} {...p}>{(title||description||actions)&&<div className={styles.sectionHeader}><div>{title&&<h2 className={styles.sectionTitle}>{title}</h2>}{description&&<p className={styles.sectionDescription}>{description}</p>}</div>{actions&&<div className={styles.headerActions}>{actions}</div>}</div>}{children}</section>}
export function Stack({as="div",direction="column",gap=3,className="",...p}){return createElement(as,{...p,className:cx(styles.stack,direction==="row"&&styles.row,styles[`gap${gap}`],className)})}
export function Grid({as="div",columns=1,gap=3,className="",style,...p}){return createElement(as,{...p,className:cx(styles.grid,className),style:{"--grid-columns":columns,"--grid-gap":`var(--space-${gap})`,...style}})}
export function Toolbar({children,className="",...p}){return <div className={cx(styles.toolbar,className)} {...p}>{children}</div>}
export function Card({as="div",interactive=false,className="",...p}){return createElement(as,{...p,className:cx(styles.card,interactive&&styles.cardInteractive,className)})}
export function Panel({header,footer,children,className="",...p}){return <section className={cx(styles.panel,className)} {...p}>{header&&<div className={styles.panelHeader}>{header}</div>}<div className={styles.panelBody}>{children}</div>{footer&&<div className={styles.panelFooter}>{footer}</div>}</section>}
export function StatCard({label,value,hint,icon,className="",...p}){return <Card className={cx(styles.statCard,className)} {...p}>{icon}{label&&<span className={styles.statLabel}>{label}</span>}<strong className={styles.statValue}>{value}</strong>{hint&&<span className={styles.statHint}>{hint}</span>}</Card>}
export const Spinner=forwardRef(function Spinner({label="Loading",className="",...p},ref){return <span ref={ref} className={cx(styles.spinner,className)} role="status" aria-label={label} {...p}/>});
export const Button=forwardRef(function Button({as="button",variant="primary",size="md",bare=false,loading=false,disabled=false,className="",children,...p},ref){const C=as;return <C ref={ref} type={C==="button"?(p.type||"button"):p.type} className={cx(!bare&&styles.button,!bare&&styles[variant],!bare&&styles[`button${size[0].toUpperCase()}${size.slice(1)}`],loading&&styles.buttonLoading,className)} disabled={C==="button"?(disabled||loading):undefined} aria-disabled={C!=="button"?(disabled||loading):undefined} {...p}>{loading?<><Spinner className={styles.buttonSpinner}/><span className={styles.buttonContentLoading}>{children}</span></>:children}</C>});
export const IconButton=forwardRef(function IconButton({label,className="",...p},ref){return <Button ref={ref} className={cx(styles.iconButton,className)} aria-label={label} title={p.title||label} {...p}/>});
export function FormField({label,htmlFor,help,error,required=false,children,className=""}){const generated=useId(),id=htmlFor||generated;const child=isValidElement(Children.only(children))?cloneElement(Children.only(children),{id:Children.only(children).props.id||id,"aria-invalid":error||undefined}):children;return <div className={cx(styles.field,className)}>{label&&<label className={styles.label} htmlFor={id}>{label}{required&&<span className={styles.required}> *</span>}</label>}{child}{help&&<p className={styles.help}>{help}</p>}{error&&<p className={styles.error} role="alert">{error}</p>}</div>}
export function FormRow({columns=2,className="",style,...p}){return <div className={cx(styles.formRow,className)} style={{"--form-columns":columns,...style}} {...p}/>}
export const Input=forwardRef(function Input({bare=false,className="",...p},ref){return <input ref={ref} {...p} className={cx(!bare&&styles.control,className)}/>});export const Select=forwardRef(function Select({bare=false,className="",...p},ref){return <select ref={ref} {...p} className={cx(!bare&&styles.control,className)}/>});export const Textarea=forwardRef(function Textarea({bare=false,className="",...p},ref){return <textarea ref={ref} {...p} className={cx(!bare&&styles.control,!bare&&styles.textarea,className)}/>});export const Checkbox=forwardRef(function Checkbox({label,...p},ref){return <label className={styles.checkboxLabel}><input ref={ref} type="checkbox" {...p} className={styles.checkbox}/><span>{label}</span></label>});
export function Badge({variant="neutral",className="",...p}){return <span className={cx(styles.badge,variant!=="neutral"&&styles[`badge${variant[0].toUpperCase()}${variant.slice(1)}`],className)} {...p}/>};export function Alert({variant="neutral",className="",...p}){return <div role={variant==="danger"?"alert":"status"} className={cx(styles.alert,variant!=="neutral"&&styles[`alert${variant[0].toUpperCase()}${variant.slice(1)}`],className)} {...p}/>}
export function EmptyState({title,description,action,icon,className="",...p}){return <div className={cx(styles.emptyState,className)} {...p}><div>{icon}{title&&<h3 className={styles.emptyTitle}>{title}</h3>}{description&&<p className={styles.emptyDescription}>{description}</p>}{action&&<div className={styles.emptyAction}>{action}</div>}</div></div>}
export function Skeleton({width="100%",height=16,className="",style,...p}){return <span className={cx(styles.skeleton,className)} style={{display:"block",width,height,...style}} aria-hidden="true" {...p}/>}
export function Table({className="",...p}){return <table className={cx(styles.table,className)} {...p}/>};export function TableContainer({className="",...p}){return <div className={cx(styles.tableContainer,className)} {...p}/>}
export function Tabs({items=[],value,onChange,label="Sections",className=""}){return <div className={cx(styles.tabs,className)} role="tablist" aria-label={label}>{items.map(i=>{const key=i.value??i.key,active=key===value;return <button key={key} type="button" role="tab" aria-selected={active} className={cx(styles.tab,active&&styles.tabActive)} onClick={()=>onChange?.(key)}>{i.label}</button>})}</div>}
export function Modal({open,onClose,title,description,children,footer,size="md",className=""}){const ref=useRef(null),previous=useRef(null),titleId=useId();useEffect(()=>{if(!open)return;previous.current=document.activeElement;const overflow=document.body.style.overflow;document.body.style.overflow="hidden";ref.current?.focus();const key=e=>e.key==="Escape"&&onClose?.();document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);document.body.style.overflow=overflow;previous.current?.focus?.()}},[open,onClose]);if(!open)return null;return <div className={styles.modalBackdrop} onMouseDown={e=>e.target===e.currentTarget&&onClose?.()}><section ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby={titleId} className={cx(styles.modal,size==="sm"&&styles.modalSm,size==="lg"&&styles.modalLg,className)}><header className={styles.modalHeader}><div><h2 id={titleId} className={styles.modalTitle}>{title}</h2>{description&&<p className={styles.modalDescription}>{description}</p>}</div><IconButton label="Close" variant="ghost" onClick={onClose}>×</IconButton></header>{children&&<div className={styles.modalBody}>{children}</div>}{footer&&<footer className={styles.modalFooter}>{footer}</footer>}</section></div>}
