export const PPE_ISSUE_ITEMS = [
  { id: "lightweightGloves", label: "Lightweight Gloves" },
  { id: "leatherGloves", label: "Leather Gloves" },
  { id: "weldingGloves", label: "Welding Gloves" },
  { id: "safetyGlasses", label: "Safety Glasses" },
  { id: "mask3m", label: "3M Safety Mask" },
  { id: "earPlugs", label: "Ear Plugs" },
  { id: "earDefenders", label: "Ear Defenders" },
  { id: "overalls", label: "Overalls" },
];

export const HS_REGISTER_TEMPLATE = [
  {
    id: "cutting-fluid-ph",
    section: "Date inspections",
    area: "inspection",
    item: "Cutting fluid pH check",
    frequency: "Weekly",
    frequencyWeeks: 1,
    owner: "Workshop",
    certificateRequired: true,
    evidenceLabel: "pH record",
  },
  {
    id: "pat-testing",
    section: "Date inspections",
    area: "inspection",
    item: "PAT testing",
    frequency: "Annual",
    frequencyWeeks: 52,
    owner: "Workshop",
    certificateRequired: true,
    evidenceLabel: "PAT certificate",
  },
  {
    id: "fire-safety",
    section: "Date inspections",
    area: "inspection",
    item: "Fire safety inspection",
    frequency: "Annual",
    frequencyWeeks: 52,
    owner: "Workshop",
    certificateRequired: true,
    evidenceLabel: "Fire safety certificate",
  },
  {
    id: "fire-alarm-service",
    section: "Date inspections",
    area: "inspection",
    item: "Fire alarm service",
    frequency: "6 months",
    frequencyWeeks: 26,
    owner: "Workshop",
    certificateRequired: true,
    evidenceLabel: "Service certificate",
  },
  {
    id: "mask-fitting",
    section: "Date inspections",
    area: "inspection",
    item: "Mask fitting",
    frequency: "2 years",
    frequencyWeeks: 104,
    owner: "H&S",
    certificateRequired: true,
    evidenceLabel: "Fit test record",
  },
  {
    id: "health-screening",
    section: "Date inspections",
    area: "inspection",
    item: "Health screening",
    frequency: "Annual",
    frequencyWeeks: 52,
    owner: "H&S",
    certificateRequired: true,
    evidenceLabel: "Health screening record",
  },
  {
    id: "gas",
    section: "Date inspections",
    area: "inspection",
    item: "Gas regulator",
    frequency: "Annual",
    frequencyWeeks: 52,
    owner: "Workshop",
    certificateRequired: true,
    evidenceLabel: "Gas certificate",
  },
  {
    id: "eicr-pat",
    section: "Date inspections",
    area: "inspection",
    item: "EICR / PAT test",
    frequency: "5 years",
    frequencyWeeks: 260,
    owner: "Workshop",
    certificateRequired: true,
    evidenceLabel: "Electrical certificate",
  },
  {
    id: "weekly-workshop-check",
    section: "Workshop checks",
    area: "workshop",
    item: "Workshop weekly check",
    frequency: "Weekly",
    owner: "Workshop",
    certificateRequired: false,
    evidenceLabel: "Checklist",
    notes: "Tidy, fire alarm, emergency exits, batteries.",
  },
  {
    id: "electrical-equipment",
    section: "Workshop checks",
    area: "workshop",
    item: "Electrical equipment",
    frequency: "Weekly",
    owner: "Workshop",
    certificateRequired: false,
    evidenceLabel: "Checklist",
  },
  {
    id: "machine-guards",
    section: "Workshop checks",
    area: "workshop",
    item: "Machine guards",
    frequency: "Weekly",
    owner: "Workshop",
    certificateRequired: false,
    evidenceLabel: "Checklist",
  },
  {
    id: "slip-trip-hazards",
    section: "Workshop checks",
    area: "workshop",
    item: "Slip/trip hazards",
    frequency: "Weekly",
    owner: "Workshop",
    certificateRequired: false,
    evidenceLabel: "Checklist",
  },
  {
    id: "emergency-lighting",
    section: "Workshop checks",
    area: "workshop",
    item: "Emergency lighting",
    frequency: "Weekly",
    owner: "Workshop",
    certificateRequired: false,
    evidenceLabel: "Checklist",
  },
  {
    id: "rest-room-hygiene",
    section: "Workshop checks",
    area: "workshop",
    item: "Rest room hygiene",
    frequency: "Weekly",
    owner: "Workshop",
    certificateRequired: false,
    evidenceLabel: "Checklist",
  },
  {
    id: "ppe-issue-register",
    section: "PPE per person",
    area: "ppe",
    item: "Employee PPE issue register",
    frequency: "Per person",
    owner: "H&S",
    certificateRequired: false,
    evidenceLabel: "PPE issue log",
    notes: "Log PPE issued to each employee with automatic issue dates and retained history.",
  },
  {
    id: "staff-training",
    section: "Training & records",
    area: "training",
    item: "Staff training",
    frequency: "As required",
    owner: "H&S",
    certificateRequired: true,
    evidenceLabel: "Training record",
  },
  {
    id: "first-aid-training",
    section: "Training & records",
    area: "training",
    item: "First aid training",
    frequency: "Renewal date",
    owner: "H&S",
    certificateRequired: true,
    evidenceLabel: "Training certificate",
  },
  {
    id: "computer-display-testing",
    section: "Training & records",
    area: "training",
    item: "Computer display testing",
    frequency: "Annual",
    owner: "H&S",
    certificateRequired: false,
    evidenceLabel: "DSE record",
  },
  {
    id: "uniform",
    section: "Training & records",
    area: "training",
    item: "Uniform",
    frequency: "As required",
    owner: "H&S",
    certificateRequired: false,
    evidenceLabel: "Issue record",
  },
  {
    id: "policy-review",
    section: "Policy review",
    area: "policy",
    item: "Policy review",
    frequency: "Annual",
    frequencyWeeks: 52,
    owner: "Management",
    certificateRequired: true,
    evidenceLabel: "Signed policy",
  },
  {
    id: "welfare-policy",
    section: "Policy review",
    area: "policy",
    item: "Welfare policy",
    frequency: "Annual",
    frequencyWeeks: 52,
    owner: "Management",
    certificateRequired: true,
    evidenceLabel: "Policy document",
  },
  {
    id: "workshop-risk-assessment",
    section: "Policy review",
    area: "policy",
    item: "Workshop risk assessment",
    frequency: "Annual",
    frequencyWeeks: 52,
    owner: "Management",
    certificateRequired: true,
    evidenceLabel: "Risk assessment",
  },
  {
    id: "tracking-risk-assessment",
    section: "Policy review",
    area: "policy",
    item: "Tracking risk assessment",
    frequency: "Annual",
    frequencyWeeks: 52,
    owner: "Management",
    certificateRequired: true,
    evidenceLabel: "Risk assessment",
  },
  {
    id: "fire-risk-assessment",
    section: "Policy review",
    area: "policy",
    item: "Fire RA",
    frequency: "Annual",
    frequencyWeeks: 52,
    owner: "Management",
    certificateRequired: true,
    evidenceLabel: "Fire risk assessment",
  },
  {
    id: "coshh",
    section: "Policy review",
    area: "policy",
    item: "COSHH",
    frequency: "Annual",
    frequencyWeeks: 52,
    owner: "Management",
    certificateRequired: true,
    evidenceLabel: "COSHH record",
  },
];

export function getHsRegisterTemplate(id) {
  return HS_REGISTER_TEMPLATE.find((item) => item.id === id) || null;
}
