export const UI_TOKENS = Object.freeze({
  radius: "var(--radius-md)", radiusSm: "var(--radius-md)", radiusXs: "var(--radius-sm)", radiusLg: "var(--radius-lg)",
  gap: "var(--space-3)", shadow: "var(--shadow-sm)", shadowSm: "var(--shadow-sm)", shadowMd: "var(--shadow-md)", shadowHover: "var(--shadow-md)",
  border: "var(--border-default)", borderSoft: "var(--border-default)", line: "var(--color-border)", softLine: "var(--color-border-strong)",
  bg: "var(--color-canvas)", bgAlt: "var(--color-surface-subtle)", page: "var(--color-canvas)", card: "var(--color-surface)", panel: "var(--color-surface)", panelTint: "var(--color-surface)", paper: "var(--color-surface)", shell: "var(--color-surface)", shellAlt: "var(--color-surface-subtle)", subHeader: "var(--color-canvas)",
  text: "var(--color-text)", ink: "var(--color-text)", dark: "var(--color-text)", muted: "var(--color-text-muted)", subtext: "var(--color-text-muted)", neutral: "var(--color-text-muted)", grid: "var(--color-text-muted)", header: "var(--color-border)",
  brand: "var(--color-brand)", blue: "var(--color-brand)", teal: "var(--color-brand)", service: "var(--color-brand)", noteFg: "var(--color-brand-hover)",
  brandSoft: "var(--color-brand-soft)", softBlue: "var(--color-brand-soft)", slateSoft: "var(--color-brand-soft)", chipBg: "var(--color-brand-soft)",
  brandBorder: "var(--color-brand-border)",
  accent: "var(--color-accent)", accentSoft: "var(--color-accent-soft)",
  successText: "var(--color-success)", successSoft: "var(--color-success-soft)", green: "var(--color-success)", good: "var(--color-success)", ok: "var(--color-success)", okFg: "var(--color-success)",
  greenSoft: "var(--color-success-soft)", greenBg: "var(--color-success-soft)", goodSoft: "var(--color-success-soft)", goodBg: "var(--color-success-soft)", okSoft: "var(--color-success-soft)", okBg: "var(--color-success-soft)", noteBg: "var(--color-success-soft)", tealBg: "var(--color-success-soft)",
  greenBorder: "var(--color-success-border)", goodBorder: "var(--color-success-border)", okBorder: "var(--color-success-border)", noteBorder: "var(--color-success-border)", tealBorder: "var(--color-success-border)",
  warn: "var(--color-warning)", warnFg: "var(--color-warning)", warnText: "var(--color-warning)", amber: "var(--color-warning)", maintenance: "var(--color-warning)", soonFg: "var(--color-warning)",
  warnSoft: "var(--color-warning-soft)", warnBg: "var(--color-warning-soft)", amberSoft: "var(--color-warning-soft)", soonBg: "var(--color-warning-soft)",
  warnBorder: "var(--color-warning-border)", warningBorder: "var(--color-warning-border)", amberBorder: "var(--color-warning-border)", soonBorder: "var(--color-warning-border)",
  danger: "var(--color-danger)", dangerText: "var(--color-danger)", dangerFg: "var(--color-danger)", red: "var(--color-danger)", mot: "var(--color-danger)", overdueFg: "var(--color-danger)",
  dangerSoft: "var(--color-danger-soft)", dangerBg: "var(--color-danger-soft)", redSoft: "var(--color-danger-soft)", redBg: "var(--color-danger-soft)", overdueBg: "var(--color-danger-soft)",
  dangerBorder: "var(--color-danger-border)", redBorder: "var(--color-danger-border)", dueMot: "var(--color-danger-border)", overdueBorder: "var(--color-danger-border)",
  purple: "var(--color-info)", blueBg: "var(--color-info-soft)", purpleBg: "var(--color-info-soft)", purpleSoft: "var(--color-info-soft)", bookedBg: "var(--color-info-soft)", bookedFg: "var(--color-brand)",
  purpleBorder: "var(--color-info-border)", bookedBorder: "var(--color-info-border)", dueService: "var(--color-info-border)",
  neutralSoft: "var(--color-surface-hover)", softSlate: "var(--color-surface-hover)", soft: "var(--color-surface-subtle)",
});
